# Generated by Django 4.1 on 2022-09-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityMap",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("place", models.CharField(max_length=50)),
                ("details", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=200, null=True)),
                ("how", models.CharField(max_length=50, null=True)),
                ("website", models.CharField(max_length=100, null=True)),
            ],
            options={
                "ordering": ["id"],
                "index_together": {("id", "place")},
            },
        ),
    ]
