# Generated by Django 4.1 on 2022-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitymap",
            name="lat",
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="activitymap",
            name="long",
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
