# Generated by Django 4.1 on 2022-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_activitymap_lat_activitymap_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitymap",
            name="lat",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitymap",
            name="long",
            field=models.IntegerField(null=True),
        ),
    ]
