# Generated by Django 4.1 on 2022-09-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="familydetail",
            table="family_detail",
        ),
    ]
