# Generated by Django 4.1 on 2022-09-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0002_alter_familydetail_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familydetail",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="familydetail",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=200, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="img",
            field=models.ImageField(upload_to="family/%Y/%m/%d"),
        ),
        migrations.AlterIndexTogether(
            name="familydetail",
            index_together={("id", "slug")},
        ),
        migrations.AlterModelTable(
            name="familydetail",
            table=None,
        ),
        migrations.RemoveField(
            model_name="familydetail",
            name="regist_dt",
        ),
        migrations.RemoveField(
            model_name="familydetail",
            name="update_dt",
        ),
    ]
