# Generated by Django 4.1 on 2022-09-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0003_alter_familydetail_options_familydetail_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familydetail",
            name="img",
            field=models.ImageField(upload_to="family"),
        ),
    ]
